### ISSUE TITLE
Is this going to be added to the official stable repo?

### ISSUE THREAD

**Issue by red8888** [godaddy/kubernetes-external-secrets#101]
just curious why this hasn't been added to the official repo yet: https://github.com/helm/charts/search?q=kubernetes-external-secrets&unscoped_q=kubernetes-external-secrets

I cant just do `helm install --name kubernetes-external-secrets --set env.AWS_REGION='<aws-region>' stable/kubernetes-external-secrets` without downloading the chart locally first

**Comment by silasbw** [comment]
Yes, I think @keweilu is working on it!

**Comment by red8888** [comment]
Awesome thanks! will make it so convenient!

**Comment by volkert-fastned** [comment]
In the meantime, you can use the `helm-github` plugin as a workaround to install the kubernetes-external-secrets chart directly from the GitHub repository:

```bash
helm plugin install --version master https://github.com/sagansystems/helm-github.git
helm github install --repo https://github.com/godaddy/kubernetes-external-secrets.git \
                              --path charts/kubernetes-external-secrets \
                              --name kubernetes-external-secrets \
                              --set env.AWS_REGION='<aws-region>'
```

**Comment by red8888** [comment]
Thats neat I didn't know about that plugin. just curious are there requirements to get a helm chart added to the official repo? I have never done that. Do they require you have tests or perform any kind of validation before accepting it?

**Comment by bilby91** [comment]
Hello! Is there any ETA for getting this in the official stable repo ? 

The issue that I found so far with the `github` plugin is that it doesn't support `helm upgrade --install`

**Comment by jeffpearce** [comment]
Hi @bilby91 . I'm not sure how long the process normally takes, but the [PR has been submitted](https://github.com/helm/charts/pull/15465). Hopefully someone from helm can look at it soon

**Comment by bilby91** [comment]
Thanks for the PR link @jeffpearce !!

**Comment by Flydiverny** [comment]
An alternative to this is for godaddy to have its own chart repo and add the godaddy chart repo to helm hub (https://github.com/helm/hub) 

Its possible to host the charts in a github repository using tools like https://github.com/helm/chart-releaser and https://github.com/helm/chart-testing you can get a pretty good setup as well :)

**Comment by keweilu** [comment]
it's in helm hub now https://hub.helm.sh/charts/external-secrets/kubernetes-external-secrets
