### ISSUE TITLE
What is EVENTS_INTERVAL_MILLISECONDS?

### ISSUE THREAD

**Issue by whereisaaron** [godaddy/kubernetes-external-secrets#126]
The configuration documentation in README and helm chart refer to a EVENTS_INTERVAL_MILLISECONDS configuration, but nothing in the code seems to use it?

**Comment by Flydiverny** [comment]
Its usage was removed in #107 when we started using the watch api instead of polling kubernetes api in every `EVENTS_INTERVAL_MILLISECONDS` for the external secrets.

**Comment by whereisaaron** [comment]
Oh great. Nice improvement. 👏
