### ISSUE TITLE
is there a custom resource definition I can install directly with kubectl?

### ISSUE THREAD

**Issue by red8888** [godaddy/kubernetes-external-secrets#145]
Unfortunately due to the infuriating inability to order your chart dependancies it seems I cant just include this chart as a requirement for my own charts that use it. I need to install the CRD first otherwise charts that use the resource fail because it has not been installed yet.

I have multiple helm deployments that each have their own kubernetes-external-secrets deployment- this works out well as a way to give each deployment access to different secrets

I really hope there is a fix for being able to order my requirements but till then need a way to just install the definition first.

**Comment by red8888** [comment]
I can install the chart and delete the deployment to get it installed but eh

```
	# Issue with ordering dependancies in helm means we have to install custom resources first manually
	# Create AWS secrets (otherwise deploy of crd will fail) and use chart to create an external-secrets deployment which will create the crd
	# Then delete everything
	kubectl create namespace temp
	kubectl create secret generic --namespace temp aws-credentials \
		--from-literal=id=$(call get_asm_secret_string, $(AWS_SM_IAM_USER_ACCESS_KEYS),AWS_ACCESS_KEY_ID) \
		--from-literal=key=$(call get_asm_secret_string, $(AWS_SM_IAM_USER_ACCESS_KEYS),AWS_SECRET_ACCESS_KEY) \
		|| true
	helm install --name install-custom-resource-external-secrets helm-chart/kubernetes-external-secrets-chart/ --namespace temp --wait || true
	helm del install-custom-resource-external-secrets --purge
	kubectl delete namespace temp
	echo confirm externalsecrets.kubernetes-client.io was created
	kubectl get crd
```

**Comment by max-lobur** [comment]
I don't think so, CRD is created by the runtime (which is weird) so you can't split
https://github.com/godaddy/kubernetes-external-secrets/blob/e26f75ca3c56b5f6dba13d581f28bdda3cd28efc/custom-resource-manifest.json
Hope this helps

**Comment by Flydiverny** [comment]
The CRD which is loaded and installed in runtime is available here:
https://github.com/godaddy/kubernetes-external-secrets/blob/master/crd.yaml
