### ISSUE TITLE
Namespace requirement in external secrets

### ISSUE THREAD

**Issue by dhineshbabuelango** [godaddy/kubernetes-external-secrets#180]
We are using AWS EKS, we are using this external-secrets option. When I downloaded the yaml file put in the link, the namespace for this controller is mentioned as kubernetes-external-secrets. But only if we put this controller in kube-system namespace it is working. Is there any namespace level restriction we have for this controller pod.  Also since we are using AWS EKS, we dont need any additional role for this pod right as the pod can assume the secrets manager role from the worker node itself. 

Sorry to post this here, but I dont know the discussions forum page.

**Comment by runningman84** [comment]
For me it looks like even in the kube-system namespace it is not able to access other namespaces:
```
{"level":50,"time":1571928563655,"pid":18,"hostname":"kube-external-secrets-kubernetes-external-secrets-5bc5445d9x4v7","type":"Error","stack":"Error: namespaces \"wp-teachtoprotect\" is forbidden: User \"system:serviceaccount:kube-system:kube-external-secrets-kubernetes-external-secrets\" cannot get resource \"namespaces\" in API group \"\" in the namespace \"wp-teachtoprotect\"\n    at _request (/app/node_modules/kubernetes-client/backends/request/client.js:214:25)\n    at Request.request [as _callback] (/app/node_modules/kubernetes-client/backends/request/client.js:162:14)\n    at Request.self.callback (/app/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:189:13)\n    at Request.EventEmitter.emit (domain.js:441:20)\n    at Request.<anonymous> (/app/node_modules/request/request.js:1161:10)\n    at Request.emit (events.js:189:13)\n    at Request.EventEmitter.emit (domain.js:441:20)\n    at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1083:12)\n    at Object.onceWrapper (events.js:277:13)","code":403,"statusCode":403,"msg":"failure while polling the secret wp-example-wordpress","v":1}
```

**Comment by Flydiverny** [comment]
[external-secrets.yml](https://github.com/godaddy/kubernetes-external-secrets/blob/master/external-secrets.yml) was missing required namespace rbac (see diff in #195)
