### ISSUE TITLE
helm chart versioning not maintained

### ISSUE THREAD

**Issue by farshad-hobsons** [godaddy/kubernetes-external-secrets#182]
Looks like multiple helm charts are not maintained on every update to the helm chart.

```bash
$helm search external-secrets -l
NAME                                        	CHART VERSION	APP VERSION	DESCRIPTION
external-secrets/kubernetes-external-secrets	1.0.1        	1.6.0      	Kubernetes External 
```

Updating in place and keeping the same `CHART VERSION` blocks users to use an older chart that worked for them. This limitation to use the same chart version can create production issues in case of backward incompatible changes.

**Comment by runningman84** [comment]
What is the chart repo url?

**Comment by keweilu** [comment]
@runningman84 chart is in https://hub.helm.sh/charts/external-secrets/kubernetes-external-secrets
@farshad-hobsons Thanks for raising this issue. We separated the application release and chart release, hope it will resolve this issue

**Comment by runningman84** [comment]
Great please add the chart url to the Readme.

**Comment by farshad-hobsons** [comment]
Thank you @keweilu, charts seem to be versioned now. This will help users to pin and rollback to specific chart versions.
```
bash-5.0# helm repo add external-secrets https://godaddy.github.io/kubernetes-external-secrets/
"external-secrets" has been added to your repositories

bash-5.0# helm search external-secrets -l
NAME                                        	CHART VERSION	APP VERSION	DESCRIPTION
external-secrets/kubernetes-external-secrets	1.1.0        	1.6.0      	Kubernetes External Secrets CustomResourceDefinition
external-secrets/kubernetes-external-secrets	1.0.1        	1.6.0      	Kubernetes External Secrets CustomResourceDefinition
```
cc: @mmcaya
