### ISSUE TITLE
Encryption in transit

### ISSUE THREAD

**Issue by brunocous** [godaddy/kubernetes-external-secrets#187]
I was wondering if there is any form of encryption in flight between AWS Secrets Manager and the k8s secret? 
If not, is it correct that the secrets travel in plain text?

**Comment by moolen** [comment]
The connection `external-secret -> AWS Secrets Manager` is [encrypted](https://docs.aws.amazon.com/de_de/general/latest/gr/rande.html#asm_region) and also the `external-secret -> Kubernetes API Server`. Both use https
