### ISSUE TITLE
Instructions for creating the secret

### ISSUE THREAD

**Issue by rluo-guardant** [godaddy/kubernetes-external-secrets#188]
Hi,

I am creating this secret on an EKS cluster - maybe I am missing some steps.
I'm following the steps here:

Save the file and run:

`kubectl apply -f hello-service-external-secret.yml`
Wait a few minutes and verify that the associated Secret has been created:

Now I run `kubectl apply -f hello-service-external-secret.yaml` and it returns:
`externalsecret.kubernetes-client.io/hello-service configured`

I see the secret in secret manager:
`
aws secretsmanager get-secret-value --secret-id hello-service/password 
`
`
{
    "Name": "hello-service/password", 
    "VersionId": "XXXX-XX-XXX-XXX-XXXX", 
    "SecretString": "1234", 
    "VersionStages": [
        "AWSCURRENT"
    ], 
    "CreatedDate": 1572285839.843, 
    "ARN": "arn:aws:secretsmanager:us-west-2:XXX:secret:hello-service/password-XXX"
}
`

I just don't see it when I run `kubectl get secret hello-service -o=yaml`

`Error from server (NotFound): secrets "hello-service" not found`

Can someone help me with this?

**Comment by moolen** [comment]
Hey @rluo-guardant! 

First, please check the logs of the `external-secrets` pod. It probably has meaningful error message. 

First guess: Your worker nodes might not have permissions to access the secret `arn:aws:secretsmanager:us-west-2:503903755075:secret:hello-service/password-nX7ClF`.
