### ISSUE TITLE
2.2.0 Failing with TypeError: Cannot destructure property `versionStage` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by iAnomaly** [godaddy/kubernetes-external-secrets#220]
@furikake @Flydiverny 2.2.0 poller is failing for ExternalSecrets WITHOUT the new `versionStage` property with error:
`TypeError: Cannot destructure property `versionStage` of 'undefined' or 'null'.`

I will open a PR if I fix it locally.

**Comment by Flydiverny** [comment]
Is this using `dataFrom` ? 

https://github.com/godaddy/kubernetes-external-secrets/blob/39fe03ffdeab64b8c9230f8993feb242ea168eba/lib/backends/kv-backend.js#L63

Should probably send `keyOptions: {}` here
