### ISSUE TITLE
[BUG]: Release 2.2 doesn't create crd

### ISSUE THREAD

**Issue by alexey-boyko** [godaddy/kubernetes-external-secrets#231]
When you deploy release 2.2 it will not create crd "externalsecrets.kubernetes-client.io" in release 2.1 everything is fine.

**Comment by Flydiverny** [comment]
Any log output? Kubernetes version? Environment?

**Comment by alexey-boyko** [comment]
aws eks, k8s 1.13, don't see any errors about that, I tried several times to deploy 2.1 2.2 in another cluster and same trouble 2.1 is fine
