### ISSUE TITLE
kubernetes-external-secrets/master/external-secrets.yml no longer exists in repo

### ISSUE THREAD

**Issue by JohnZucker** [godaddy/kubernetes-external-secrets#236]
Hi - Apologies if I missed an announcement about this
1. The doc still says https://raw.githubusercontent.com/godaddy/kubernetes-external-secrets/master/external-secrets.yml is available  (https://uk.godaddy.com/engineering/2019/04/16/kubernetes-external-secrets/)
2. Whatever the advantages of helm, the above has been a trusted and reliable way of getting external-secrets deployed in every one of our clusters.

Until recent days.

Now we get the following:
$ curl https://raw.githubusercontent.com/godaddy/kubernetes-external-secrets/master/external-secrets.yml
404: Not Found

Correspondingly we are broken when it comes to deploying new externalsecrets.

Please advise:
Are we compelled to use helm as the deployment route, or alternatively have you backed up a copy of external-secrets.yml  somewhere. We are looking to support external-secrets 1.6.0 at this time.

**Comment by Flydiverny** [comment]
Recommended approach if you want to install with kubectl is to use `helm template` to generate the manifests
https://github.com/godaddy/kubernetes-external-secrets#install-with-kubectl

Last version of the external-secrets.yml that was in the repo can be found here:
https://raw.githubusercontent.com/godaddy/kubernetes-external-secrets/24421b925e52a3930097a14b8727bb54560d2632/external-secrets.yml
