### ISSUE TITLE
Support  IAM roles for service accounts

### ISSUE THREAD

**Issue by dudicoco** [godaddy/kubernetes-external-secrets#240]
The new feature which supports assigning IAM roles directly to pods was recently released:
https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/

Currently, the kubernetes-external-secrets pod is not able to assume the role and is using the node assigned role instead, although the aws-sdk version in nodejs supports the new feature.

**Comment by Flydiverny** [comment]
@dudicoco Have you checked all the kinks in the previous issue? https://github.com/godaddy/kubernetes-external-secrets/issues/164

**Comment by dudicoco** [comment]
@Flydiverny I have now checked all of the related issues.
Everything seems to be configured properly on my side, but I am experiending the same issue as [ ](https://github.com/godaddy/kubernetes-external-secrets/pull/200#issuecomment-554573885)

**Comment by Flydiverny** [comment]
Somehow I managed to link to the wrong issue was meant to refer to #161 

I haven't tested this myself but my understanding is that if kiam or something else provides credentials to the pod, these are used before the IRSA credentials.

As seen here: 
https://github.com/aws/aws-sdk-js/blob/v2.575.0/lib/node_loader.js#L61-L69

Please verify that you are not using other means of providing AWS credentials to the pod that have higher priority than `TokenFileWebIdentityCredentials` which should be what is used for IRSA

**Comment by Flydiverny** [comment]
Closing this as it seems resolved by discussion in #200
