### ISSUE TITLE
No namespace for the deployment

### ISSUE THREAD

**Issue by gerrywastaken** [godaddy/kubernetes-external-secrets#253]
Shouldn't the deployment have a namespace or was this deliberately left out for some reason?
https://github.com/godaddy/kubernetes-external-secrets/blob/master/charts/kubernetes-external-secrets/templates/deployment.yaml

**Comment by Flydiverny** [comment]
Uh AFAIK you normally don't set any namespace in a helm chart? 🤔 When using `helm install` you will provide a namespace and the resources will be created within it. ie setting `namespace: {{ .Release.Namespace }}`  in the template should give the same result as not setting it at all.

**Comment by gerrywastaken** [comment]
Ok, cool, that makes sense :+1:

**Comment by ecout** [comment]
@Flydiverny  Agreed, I'm guessing the IP was thrown off by the fact that if you want to use kubectl and use the helm client to "export" the template to manifests some files have default namespace and others don't.
