### ISSUE TITLE
Fargate Support

### ISSUE THREAD

**Issue by cabrinha** [godaddy/kubernetes-external-secrets#254]
Hello, now EKS has Fargate as a supported runtime. In this environment, there are no nodes and no ec2 metadata endpoint.

I tried to run external-secrets in a fargate context and I got errors about failing to connect the the metadata endpoint.

What works well for me is using IAM Roles for Service Accounts, as outlined here: https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html

However, when the runtime is Fargate, I still get those ec2 metadata endpoint errors.

Is there a way we can use Helm to pass in configuration parameters that the service could be looking for in ec2 metadata?

I'm assuming the issue is here: https://github.com/godaddy/kubernetes-external-secrets/blob/master/config/aws-config.js#L45

And what may be needed here is an option for specifying "Assume Role with Web Identity" instead of just "Assume Role".

**Comment by Flydiverny** [comment]
If its the assume role thing I think the same issue you are experiencing should be reproducible without Fargate or do they limit more there? Haven't had the opportunity to test neither IRSA nor eks+fargate yet.

For reference https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/STS.html#assumeRoleWithWebIdentity-property

**Comment by cabrinha** [comment]
I think that the Assume Role call will check the ec2 metadata endpoint where Assume Role with Web Identity will not: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_request.html#stsapi_comparison

```
Assume Role - IAM user or IAM role with existing temporary security credentials
AssumeRoleWithWebIdentity- Any user; caller must pass a web identity token that indicates authentication from a known identity provider
```

Because Assume Role needs and IAM user or IAM Role, I'm thinking it's hitting that ec2 metadata endpoint to get the user or role making the call.

Assume Role with Web Identity doesn't require any user, just a web identity token.

**Comment by lukaszbudnik** [comment]
Same for me. 

I can get kubernetes-external-secrets working on "old"  EKS, but it fails on Fargate.

I think the fix should be to rely on the default AWS SDK credentials chain provider (I have a go app which uses AWS GO SDK it and works like a charm on Fargate). I'm pretty sure node.js SDK default credentials chain provider supports it too.

For example when I execute this command on the pod I get this:

```
$ kubectl exec external-secrets-kubernetes-external-secrets-58b679b56c-skfq6 env | grep AWS
AWS_ROLE_ARN=arn:aws:iam::XXXX:role/eksctl-my-cluster-fg-addon-iamserviceac-Role1-TBWWKO4AZE1O
AWS_WEB_IDENTITY_TOKEN_FILE=/var/run/secrets/eks.amazonaws.com/serviceaccount/token
AWS_REGION=ap-northeast-1
```

**Comment by lukaszbudnik** [comment]
So yes, node.js SDK supports TokenFileWebIdentityCredentials() as a part of the default credential provider chain: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CredentialProviderChain.html#defaultProviders-property

**Comment by dalgibbard** [comment]
I couldn't make head-nor-tails of the TokenFileWebIdentityCredentials() method/docs (JS noob); but i've raised https://github.com/godaddy/kubernetes-external-secrets/pull/414 to at least make it work :)

For the interim, i've pushed this change to my own dockerhub, so you can deploy the existing helm chart with the following to test/use (examples taken from terraform, so restructure as ```--set``` if needed):
```
  set {
    name = "env.FARGATE"
    value = 1
  }

  set {
    name = "securityContext.fsGroup"
    value = 65534
  }

  set {
    name = "image.repository"
    value = "dalgibbard/kubernetes-external-secrets"
  }

  set {
    name = "image.tag"
    value = "latest"
  }
```

**Comment by lukaszbudnik** [comment]
@dalgibbard you actually reminded me that I fixed it too (didn't post update). I will open pull request with my changes for godaddy guys for reference.

I think my changes are simpler (12 lines of code) and don't require setting additional envs. I also think they are more flexible and don't refer explicitly to fargate (because you can use assumeRoleWithWebIdentity not only on Fargate).

**Comment by Flydiverny** [comment]
Merged #416, thanks for the PRs! 🎉

**Comment by dalgibbard** [comment]
@lukaszbudnik sounds good to me! Thanks :)

**Comment by dalgibbard** [comment]
This change isn't working for me;
```
<cluster_name>-us-west-2/token-file-web-identity is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::<account_number>:role/external_secrets_role_<role_name>","code":"AccessDenied","
```
For EKS Fargate, I had it working by actively reading the token from disk, and passing that into the assumeRoleWithWebIdentity method; eg adding this method:
```
function loadServiceToken () {
  return fs.readFileSync(webIdentity, 'utf8')
}
```
and then calling assumeRoleWithWebIdentity as:
```
sts.assumeRoleWithWebIdentity(merge(assumeRoleOpts, { WebIdentityToken: loadServiceToken() }), (err, res) => {
```

If you see the documentation here, , under the header 'WebIdentityToken', it does say 'Required: Yes' ?

@lukaszbudnik / @Flydiverny  -- if I change this in the PR, does it break anything for you? It says it's required; so i'm not sure how this is working for you currently?

**Comment by lukaszbudnik** [comment]
@dalgibbard what image are you using in your helm chart? 
You can use the one I pushed to my docker hub account: `lukasz/kubernetes-external-secrets:latest`. For example:

```
helm install external-secrets external-secrets/kubernetes-external-secrets \
--set image.repository='lukasz/kubernetes-external-secrets' \
--set image.tag='latest' \
--set env.AWS_REGION=us-east-2 \
--set securityContext."fsGroup"=65534 \
--set serviceAccount.annotations."eks\.amazonaws\.com/role-arn"=$IAM_ROLE_ARN \
--set podAnnotations."iam\.amazonaws\.com/role"=$IAM_ROLE_NAME 
```

**Comment by dalgibbard** [comment]
Oh I'd assumed the merge created a new container 😄 - I should really learn to assume nothing :D
Still though, when pointing it to your image instead, I get the same error?

Inside the pod, the AWS_ROLE_ARN and AWS_WEB_IDENTITY_TOKEN_FILE values are correct; and the pod/serviceaccount annotations are correct etc too.

I pushed a container to my own hub, where the only change is using the Token file contents passed into the assumeRoleWithWebIdentity, and this works great for us; see: https://github.com/godaddy/kubernetes-external-secrets/pull/417/files
My container for comparison: ```dalgibbard/kubernetes-external-secrets:latest```

I'd be super-interested to know if this change works for you still too? If it does then this might be an acceptable fix for all WebIdentity scenarios?

**Comment by dalgibbard** [comment]
^^ @lukaszbudnik in case you don't see this :)

**Comment by lukaszbudnik** [comment]
No worries. The error message you get is odd and looks like the role is not authorised to do sts:AssumeRole (which in fact it should do sts:AssumeRoleWithWebIdentity). 

For a reference I published all my commands I used for testing as a gist. The commands apart of creating Fargate cluster, and deploying custom image kubernetes-external-secrets, also include setting up policy, role and trust relationship (which I based on https://github.com/godaddy/kubernetes-external-secrets/issues/383)

Here are all my steps: https://gist.github.com/lukaszbudnik/f1f42bd5a57430e3c25034200ba44c2e
They are parameterised by 2 env variables and nothing is hardcoded so easy to reply them all.

Happy to get to the bottom of the issue.

**Comment by dalgibbard** [comment]
@lukaszbudnik -- I think I found the issue - using your image, the code change is not present?

Image ID:       docker.io/lukasz/kubernetes-external-secrets@sha256:a7e31fbe70cdeee399330bdc24b4a878e74189d34376c263825bc245fc2989e0

Contents of the file are the original (no webidentity stuff):
```
/app/config $ cat /app/config/aws-config.js | grep -i web
/app/config $
```

**Comment by dalgibbard** [comment]
OK so i grabbed master branch from this repo, pushed to my own Docker image (dalgibbard/kubernetes-external-secrets:master), and it raises this error (which i expected, because it's a required parameter for that class...):
```
{"level":50,"time":1593601198039,"pid":17,"hostname":"external-secrets-kubernetes-external-secrets-67cdc64548-nkz5m","message":"Missing required key 'WebIdentityToken' in params","code":"MissingRequiredParameter","time":"2020-07-01T10:59:58.039Z","stack":"MissingRequiredParameter: Missing required key 'WebIdentityToken' in params\n    at ParamValidator.fail (/app/node_modules/aws-sdk/lib/param_validator.js:50:37)\n    at ParamValidator.validateStructure (/app/node_modules/aws-sdk/lib/param_validator.js:61:14)\n    at ParamValidator.validateMember (/app/node_modules/aws-sdk/lib/param_validator.js:88:21)\n    at ParamValidator.validate (/app/node_modules/aws-sdk/lib/param_validator.js:34:10)\n    at Request.VALIDATE_PARAMETERS (/app/node_modules/aws-sdk/lib/event_listeners.js:126:42)\n    at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:106:20)\n    at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\n    at Request.emit (/app/node_modules/aws-sdk/lib/request.js:683:14)\n    at Request.transition (/app/node_modules/aws-sdk/lib/request.js:22:10)\n    at AcceptorStateMachine.runTo (/app/node_modules/aws-sdk/lib/state_machine.js:14:12)","type":"Error","msg":"failure while polling the secret mysecret/test"}
```
