### ISSUE TITLE
upgrading to 3.0.0 from 1.3.1

### ISSUE THREAD

**Issue by omriarieli** [godaddy/kubernetes-external-secrets#270]
Hi, im running kubernetes version 1.13, tried to upgrade to 3.0.0 to take care of:
[https://github.com/godaddy/kubernetes-external-secrets/issues/158](https://github.com/godaddy/kubernetes-external-secrets/issues/158)

which we encountered. after the upgrade somehow the external-secrets pods cannot get externalsecrets/status and getting 403. are there any steps i need to take before upgrading?

attaching error maessage:
`{"level":50,"time":1580310461134,"pid":17,"hostname":"kubernetes-external-secrets-d699db45-rsr89","type":"Error","stack":"Error: externalsecrets.kubernetes-client.io \"my-secret\" is forbidden: User \"system:serviceaccount:kube-system:kubernetes-external-secrets-service-account\" cannot get resource \"externalsecrets/status\" in API group \"kubernetes-client.io\" in the namespace \"dev\"\n    at /app/node_modules/kubernetes-client/backends/request/client.js:214:25\n    at Request._callback (/app/node_modules/kubernetes-client/backends/request/client.js:162:14)\n    at Request.self.callback (/app/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:210:5)\n    at Request.EventEmitter.emit (domain.js:476:20)\n    at Request.<anonymous> (/app/node_modules/request/request.js:1161:10)\n    at Request.emit (events.js:210:5)\n    at Request.EventEmitter.emit (domain.js:476:20)\n    at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1083:12)\n    at Object.onceWrapper (events.js:299:28)","code":403,"statusCode":403,"msg":"status check went boom for dev/my-secret","v":1}`

thanks
Omri

**Comment by Flydiverny** [comment]
If you are not using the helm chart you will need to add additional RBAC privileges that has been added to support the new features.
You can see the RBAC used in the helm chart here https://github.com/godaddy/kubernetes-external-secrets/blob/master/charts/kubernetes-external-secrets/templates/rbac.yaml
Following https://github.com/godaddy/kubernetes-external-secrets#install-with-kubectl you should be able to generate a non templated version.

**Comment by omriarieli** [comment]
Thanks, it seems to be working after adding the missing rbac.

to anyone interested whats missing is:
ClusterRole rules:
`  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["kubernetes-client.io"]
    resources: ["externalsecrets/status"]
    verbs: ["get", "update"]`

and a new ClusterRoleBinding for system:auth-delegator

`roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator`
