### ISSUE TITLE
GCP backend: Google Cloud's Secret Manager

### ISSUE THREAD

**Issue by busser** [godaddy/kubernetes-external-secrets#271]
Are there any plans to add support for [recently released](https://cloud.google.com/blog/products/identity-security/introducing-google-clouds-secret-manager) Google Cloud's Secret Manager?

As mentioned in #50, GoDaddy is focused on AWS internally. Would you have any advice for someone willing to implement a new operator for integrating GCP Secret Manager with GKE?

**Comment by iniinikoski** [comment]
This would be very interesting...

**Comment by Flydiverny** [comment]
I think PRs welcome :) we've got PRs adding both vault and azure access so I don't see why GCP backend can't be next :)

**Comment by inductor** [comment]
I'm not saying this to stop anything with this but you can use Berglas with GCP Secret Manager if you need something immediately.

**Comment by busser** [comment]
> I'm not saying this to stop anything with this but you can use Berglas with GCP Secret Manager if you need something immediately.

Yes. This what we are using for now, but it has some limitations compared to having actual Kubernetes secrets.

**Comment by karan-kap** [comment]
Submitted a PR for supporting GCP Secret Manager
https://github.com/godaddy/kubernetes-external-secrets/pull/301

**Comment by silasbw** [comment]
Included in the latest 3.2.0 release.  Thanks everyone!
