### ISSUE TITLE
New error when loading kube specs

### ISSUE THREAD

**Issue by derrickburns** [godaddy/kubernetes-external-secrets#273]
I am running on AWS 1.14.9

npm info it worked if it ends with ok                                                                                                               ││ npm WARN npm npm does not support Node.js v12.13.0                                                                                                  ││ npm WARN npm You should probably upgrade to a newer version of node as we                                                                           ││ npm WARN npm can't make any promises that npm will work with this version.                                                                          ││ npm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10, 11.                                                               ││ npm WARN npm You can find the latest version at https://nodejs.org/                                                                                 ││ npm info using npm@6.4.1                                                                                                                            ││ npm info using node@v12.13.0                                                                                                                        ││ npm info lifecycle kubernetes-external-secrets@3.0.0~prestart: kubernetes-external-secrets@3.0.0                                                    ││ npm info lifecycle kubernetes-external-secrets@3.0.0~start: kubernetes-external-secrets@3.0.0                                                       ││ > kubernetes-external-secrets@3.0.0 start /app                                                                                                      ││ > ./bin/daemon.js                                                                                                                                   ││ {"level":30,"time":1580863609725,"pid":19,"hostname":"external-secrets-kubernetes-external-secrets-6c8bf64598-6wwc8","msg":"loading kube specs","v" ││ Error: Failed to get /openapi/v2 and /swagger.json: argument fn must be a function                                                                  ││     at /app/node_modules/kubernetes-client/lib/swagger-client.js:58:15                                                                              ││     at processTicksAndRejections (internal/process/task_queues.js:93:5)                                                                             ││     at async main (/app/bin/daemon.js:32:3)                                                                                                         ││ npm info lifecycle kubernetes-external-secrets@3.0.0~start: Failed to exec start script

**Comment by krao-test** [comment]
What's the resolution for this issue?

**Comment by Flydiverny** [comment]
@krao-test same issue as in #278
