### ISSUE TITLE
STS doesnt use service account IAM role

### ISSUE THREAD

**Issue by hayderimran7** [godaddy/kubernetes-external-secrets#275]
Following the guide here https://docs.aws.amazon.com/eks/latest/userguide/create-service-account-iam-policy-and-role.html
https://docs.aws.amazon.com/eks/latest/userguide/specify-service-account-role.html
and https://docs.aws.amazon.com/eks/latest/userguide/enable-iam-roles-for-service-accounts.html
i can verify the PODS get populated with environment variable for service account and role arn
```
 # env | grep AWS_
AWS_ROLE_ARN=arn:aws:iam::496386341798:role/ROLE_NAME
AWS_WEB_IDENTITY_TOKEN_FILE=/var/run/secrets/eks.amazonaws.com/serviceaccount/token
```
the code should use these environment variables to make call like `sts.assumeRoleWithWebIdentity(params, function(err, data) {` the docs mention `IAM role for service account ` but the code is void of such functionality. 

it would be nice to extend the code to make service account IAM role feature work https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/STS.html#assumeRoleWithWebIdentity-property

**Comment by Flydiverny** [comment]
I belive the code uses the IRSA role but when using secrets where it should assume a role for the secret as well it is not assuming using the IRSA credentials.

**Comment by hayderimran7** [comment]
by help of https://github.com/godaddy/kubernetes-external-secrets/issues/161#issuecomment-540591653 i was able to got it working :)

**Comment by hayderimran7** [comment]
this was the fix 
```
helm install --namespace=default external-secrets external-secrets/kubernetes-external-secrets --set serviceAccount.annotations."eks\.amazonaws\.com/role-arn"=arn:aws:iam::<ACCOUNT_ID>:role/<ROLE_NAME> --set securityContext."fsGroup"=65534
```
the `fsGroup` must be set to that to get that working
