### ISSUE TITLE
Project is missing versions / releases

### ISSUE THREAD

**Issue by JacopoDaeli** [godaddy/kubernetes-external-secrets#28]
Title is self explaining. I propose to start versioning the project and use version numbers as tags for docker images (e.g, like [node.js](https://hub.docker.com/_/node) does).

**Comment by silasbw** [comment]
I just noticed this. I coincidentally made https://github.com/godaddy/kubernetes-external-secrets/pull/29 today. I like the idea of publishing images tagged with the module version (in addition to the short SHA1) and managing version with standard-release.  I'll look into that.

**Comment by JacopoDaeli** [comment]
🌮
