### ISSUE TITLE
Failing to assume IAM role the process already has.

### ISSUE THREAD

**Issue by jasonsteenblik** [godaddy/kubernetes-external-secrets#284]
Hello, I am attempting to use iam roles for service accounts with external-secrets. I'm deploying it with:
```
$ helm install --name  "kubernetes-external-secrets" --set securityContext.fsGroup=65534 --set serviceAccount.annotations."eks\.amazonaws\.com/role-arn"='arn:aws:iam::123456789012:role/external-secrets-role' external-secrets/kubernetes-external-secrets
```

I have the following environment variable in the pod, which appears correct to me:
```
AWS_REGION=eu-central-1
AWS_ROLE_ARN=arn:aws:iam::123456789012:role/external-secrets-role
AWS_WEB_IDENTITY_TOKEN_FILE=/var/run/secrets/eks.amazonaws.com/serviceaccount/token
```

However, it appears that external-secrets is attempting to assume the role even though it already has it. I've included the full error below but the relevant portion is `"User: arn:aws:sts::123456789012:assumed-role/external-secrets-role/token-file-web-identity is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::123456789012:role/external-secrets-role"`

If I include the ability to assume the self role in the policy attached to the role it works. This doesn't seem right to me. I'd appreaciate any feedback about whether this is the way it's working for other people. Thanks!

Full error:
```
{
    "level": 50,
    "time": 1581943424008,
    "pid": 18,
    "hostname": "kubernetes-external-secrets-5b4cb8dc4-5rw2j",
    "message": "User: arn:aws:sts::123456789012:assumed-role/external-secrets-role/token-file-web-identity is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::123456789012:role/external-secrets-role",
    "code": "AccessDenied",
    "time": "2020-02-17T12:43:44.007Z",
    "requestId": "31937f5d-7380-48d2-b058-27093a28e175",
    "statusCode": 403,
    "retryable": false,
    "retryDelay": 70.34601528496822,
    "msg": "failure while polling the secret default/test-secret",
    "stack": "AccessDenied: User: arn:aws:sts::123456789012:assumed-role/external-secrets-role/token-file-web-identity is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::123456789012:role/external-secrets-role\n    at Request.extractError (/app/node_modules/aws-sdk/lib/protocol/query.js:50:29)\n    at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:106:20)\n    at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\n    at Request.emit (/app/node_modules/aws-sdk/lib/request.js:683:14)\n    at Request.transition (/app/node_modules/aws-sdk/lib/request.js:22:10)\n    at AcceptorStateMachine.runTo (/app/node_modules/aws-sdk/lib/state_machine.js:14:12)\n    at /app/node_modules/aws-sdk/lib/state_machine.js:26:10\n    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:38:9)\n    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:685:12)\n    at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:116:18)",
    "type": "Error",
    "v": 1
}
```

**Comment by xueshanf** [comment]
@jasonsteenblik check your IAM role **external-secrets-role** on AWS iam console to see if the trust relationship conditions match up.

On the condition column: 

StringEquals | oidc.eks.eu-central-1.amazonaws.com/id/......:sub | system:serviceaccount:\<namespace\>:\<service account\>

Everything has to match your kubenertes-external-secrets deployment:  **namespace, service** **account name**.

**Comment by jasonsteenblik** [comment]
Hi @xueshanf, 
This doesn't appear to be my issue. The IRSA has done its work and the environment & token are in the pod as expected. However, it appears external secrets is attempting to call AssumeRole to assume the role it when it's not required.

The original policy assigned to the role was 
```{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": [
                "secretsmanager:ListSecretVersionIds",
                "secretsmanager:GetSecretValue",
                "secretsmanager:GetResourcePolicy",
                "secretsmanager:DescribeSecret"
            ],
            "Resource": "*"
        }
    ]
}
```

However, I've had to add the following to the policy to make it work. Keep in mind that the role listed here in the AssumeRole statement is the role assigned to the service account using the IRSA method. So allowing the role to assume itself fixed the issue.
```
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": "sts:AssumeRole",
            "Resource": "arn:aws:iam::487847171572:role/external-secrets-role"
        }
```

**Comment by emoyer0928** [comment]
Check the configuration of your external secret.  If you have a roleArn defined in your external secret, it will try to assume that role even if it is the same role as your service account.

**Comment by Niksko** [comment]
> Check the configuration of your external secret. If you have a roleArn defined in your external secret, it will try to assume that role even if it is the same role as your service account.

This sounds fixable, the `assumeRole` function should probably make a call to `sts.getCallerIdentity` to see if it already has the right role. I'll try and fix this if I have some time.

**Comment by accuracy27** [comment]
Great thanks @Niksko .

**Comment by Flydiverny** [comment]
The only point we explicitly call assume role is if the user has specified in the secret that a role should be used. So if the user specifies the same role in the external secret as the service is already running as it sounds like a configuration error to me? Or am I missing something here? :)

**Comment by accuracy27** [comment]
@Flydiverny You are correct. I've verified that it is working as expected when the role arn specified only on the service account. Thanks.
