### ISSUE TITLE
EKS: not using serviceaccount IAM role

### ISSUE THREAD

**Issue by mzupan** [godaddy/kubernetes-external-secrets#290]
I have openid setup and working for things like externaldns and cluster autoscaler. I'm trying to use the same setup for external-secrets and it's erroring with the worker IAM role not the pod IAM

My values override looks like

```
env:
  AWS_REGION: us-east-1
  AWS_ROLE_ARN: arn:aws:iam::####:role/eks-externalsecrets-production
  AWS_WEB_IDENTITY_TOKEN_FILE: /run/secrets/kubernetes.io/serviceaccount/token

serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::####:role/eks-externalsecrets-production
  name: externalsecrets

fullnameOverride: external-secrets

securityContext:
  fsGroup: 65534
```

If I exec into the container I get the following

```
/app $ env | grep AWS
AWS_ROLE_ARN=arn:aws:iam::#####:role/eks-externalsecrets-production
AWS_WEB_IDENTITY_TOKEN_FILE=/run/secrets/kubernetes.io/serviceaccount/token
AWS_REGION=us-east-1
```

My pod has the serviceaccount

```
$ kube get pod external-secrets-6fcfb4d7f6-f84hr -o yaml| grep Account
  serviceAccount: externalsecrets
  serviceAccountName: externalsecrets
      - serviceAccountToken:
```

My service account looks like

```
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::####:role/eks-externalsecrets-production
  creationTimestamp: "2020-02-25T15:42:38Z"
  labels:
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: kubernetes-external-secrets
    helm.sh/chart: kubernetes-external-secrets-3.1.0
  name: externalsecrets
  namespace: kube-system
  resourceVersion: "342896133"
  selfLink: /api/v1/namespaces/kube-system/serviceaccounts/externalsecrets
  uid: 7374a618-57e5-11ea-abd4-027cc672dfbb
secrets:
- name: externalsecrets-token-f598f
```

My IAM role for `eks-externalsecrets-production` has the trust setup

```
    {
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "Federated": "arn:aws:iam::####:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/5AEB5B511DB95146C339E4005DC9B402"
      },
      "Action": "sts:AssumeRoleWithWebIdentity",
      "Condition": {
        "StringEquals": {
          "oidc.eks.us-east-1.amazonaws.com/id/5AEB5B511DB95146C339E4005DC9B402:sub": "system:serviceaccount:kube-system:externalsecrets"
        }
      }
    }
  ]
}
```

The error I'm getting is this

```
{"level":30,"time":1582645785665,"pid":19,"hostname":"external-secrets-6fcfb4d7f6-f84hr","msg":"fetching secret property /production/secret/foobar with role: pods role","v":1}
{"level":50,"time":1582645785689,"pid":19,"hostname":"external-secrets-6fcfb4d7f6-f84hr","message":"User: arn:aws:sts::####:assumed-role/EKSWorker-production/i-0eff436735c6befc9 is not authorized to perform: ssm:GetParameter on resource: arn:aws:ssm:us-east-1:####:parameter/production/secret/foobar","code":"AccessDeniedException","time":"2020-02-25T15:49:45.689Z","requestId":"560928ed-fa39-420b-a3c4-2b109b6e6b8a","statusCode":400,"retryable":false,"retryDelay":36.41121831818457,"msg":"failure while polling the secret kube-system/foobar","stack":"AccessDeniedException: User: arn:aws:sts::####:assumed-role/EKSWorker-production/i-0eff436735c6befc9 is not authorized to perform: ssm:GetParameter on resource: arn:aws:ssm:us-east-1:022149140658:parameter/production/secret/foobar\n    at Request.extractError (/app/node_modules/aws-sdk/lib/protocol/json.js:51:27)\n    at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:106:20)\n    at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\n    at Request.emit (/app/node_modules/aws-sdk/lib/request.js:683:14)\n    at Request.transition (/app/node_modules/aws-sdk/lib/request.js:22:10)\n    at AcceptorStateMachine.runTo (/app/node_modules/aws-sdk/lib/state_machine.js:14:12)\n    at /app/node_modules/aws-sdk/lib/state_machine.js:26:10\n    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:38:9)\n    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:685:12)\n    at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:116:18)","type":"Error","v":1}
```

`EKSWorker-production` is the IAM role for the worker nodes

Am I wrong to assume this setup should work? or am I overlooking something stupid?

Thanks!

**Comment by troeng** [comment]
Hi, 
have you been able to resolve this? I have the same issue. Same setup, I have followed the guide but the error says that the role arn "xxxx-node-instance-xxx" is not authorized to ssm:GetParameter.

**Comment by troeng** [comment]
We solved it by changing following:
container env value:
- name: "AWS_ROLE_SESSION_NAME"
  value: "some-random-session-name"

spec:tepmlate:spec:securityContext:fsGroup: 1000

Role trust relationship change:
StringLike | oidc.eks.eu-central-1.amazonaws.com/id/<id>:sub | system:serviceaccount:kube-system:*

Policyupdate:
The policy must allow to assume the role itself (see this issue for background: https://github.com/godaddy/kubernetes-external-secrets/issues/284 )

**Comment by gubbin** [comment]
Tried everything listed here plus some variations, no luck so far.  Wonder if it's an EKS version issue?  We're using EKS 1.13.

**Comment by mo-saeed** [comment]
I have the same issue, @mzupan @gubbin did you find out what is the issue?

**Comment by papagala** [comment]
I have the exact same problem! Also no idea how to implement the workaround provided by @troeng .  Could you be more specific?

**Comment by emohammad** [comment]
Did any one get this to work? I got it working for some time and then when i recreated cluster it doesnt work now. I tested in another pod and service accounts work fine with aws cli

**Comment by grifx** [comment]
I am facing the same problem.

**OUR ISSUE: the sdk client from external secret node server is not automatically assuming the correct role**

By default `Node AWS sdk > 2.521.0` should do this automatically using ENV variables
https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html

### 1. My helm values
```
env:
  AWS_REGION: ap-southeast-2
  AWS_ROLE_ARN: arn:aws:iam::xxx:role/xxx
  AWS_WEB_IDENTITY_TOKEN_FILE: /run/secrets/kubernetes.io/serviceaccount/token
  AWS_ROLE_SESSION_NAME: random-session-name
  LOG_LEVEL: info

serviceAccount:
  create: false
  name: default

fullnameOverride: external-secrets

securityContext:
  fsGroup: 65534
```

### 2. Ensure the context is correct

`kubectl exec -it external-secrets-5678b548d6-pk6n5 -- sh`

```
$ printenv | grep AWS
AWS_ROLE_ARN=arn:aws:iam::xxx:role/xxx
AWS_WEB_IDENTITY_TOKEN_FILE=/run/secrets/kubernetes.io/serviceaccount/token
AWS_ROLE_SESSION_NAME=random-session-name
AWS_REGION=ap-southeast-2

$ ls -all /var/run/secrets/kubernetes.io/serviceaccount/token
lrwxrwxrwx    1 root     root            12 Mar 17 01:26 /var/run/secrets/kubernetes.io/serviceaccount/token -> ..data/token

$ ls -all /var/run/secrets/kubernetes.io/serviceaccount/..2020_03_17_01_26_42.641118408/token
-rw-r--r--    1 root     nobody         842 Mar 17 01:26 /var/run/secrets/kubernetes.io/serviceaccount/..2020_03_17_01_26_42.641118408/token
```

### 3. Find out which caller identity is used

You can try many aws-sdk versions `$ npx -p aws-sdk@VERSION node -r aws-sdk`

`$ npx -p aws-sdk node -r aws-sdk`

```
const AWS = require('aws-sdk');

const stsDefault = new AWS.STS();
stsDefault.getCallerIdentity({}, console.log);

const stsWithCredentials = new AWS.STS({credentials: new AWS.TokenFileWebIdentityCredentials()});
stsWithCredentials.getCallerIdentity({}, console.log);
```

### 4. Result

#### Without Credentials
```
{
  ResponseMetadata: { RequestId: '4465fce7-1044-4388-99ba-3dd94c05846b' },
  UserId: 'xxxxxx',
  Account: 'xxxx',
  Arn: 'arn:aws:sts::xxx:assumed-role/xxx-autoscalinggroupondemand'
}
```

#### With Credentials

```
Error [CredentialsError]: Missing credentials in config
    at Request.extractError (/app/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/app/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/app/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/app/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /app/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  message: 'Missing credentials in config',
  code: 'CredentialsError',
  time: 2020-03-17T02:22:47.634Z,
  requestId: 'b172ec41-f4f2-4f8c-ab25-f3e2c24ddae0',
  statusCode: 400,
  retryable: true,
  originalError: {
    message: 'Could not load credentials from TokenFileWebIdentityCredentials',
    code: 'CredentialsError',
    time: 2020-03-17T02:22:47.634Z,
    requestId: 'b172ec41-f4f2-4f8c-ab25-f3e2c24ddae0',
    statusCode: 400,
    retryable: true,
    originalError: {
      message: 'Missing a required claim: aud',
      code: 'InvalidIdentityToken',
      time: 2020-03-17T02:22:47.634Z,
      requestId: 'b172ec41-f4f2-4f8c-ab25-f3e2c24ddae0',
      statusCode: 400,
      retryable: true
    }
  }
}
```

@farshad-hobsons from https://github.com/aws/aws-sdk-js/issues/2848 (I hope you don't mind the ping) concludes it's not an aws issue. I'm not sure why. I set the correct fsGroup value.

```
securityContext:
  fsGroup: 65534
```

**Comment by grifx** [comment]
### More insights:

When nodeJs AWS SDK tries to resolve Credentials. It goes through all those Credential Providers:
```
EnvironmentCredentials
SharedIniFileCredentials
ECSCredentials
ProcessCredentials
TokenFileWebIdentityCredentials
EC2MetadataCredentials
```

Because the TokenFileWebIdentityCredentials isn't working, the Sdk fallbacks to the EC2MetadataCredentialsProvider. Which explains our issue.

### Why TokenFileWebIdentityCredentials doesn't work?

The SDK seems to work properly. The Following request is dispatched:

```
https://sts.amazonaws.com/?
Action=AssumeRoleWithWebIdentity&
RoleArn=ARN
RoleSessionName=this-is-a-test&
Version=2011-06-15&
WebIdentityToken=TOKEN
```

The STS API returns the following error:

```
<ErrorResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/">
<Error>
<Type>Sender</Type>
<Code>InvalidIdentityToken</Code>
<Message>Missing a required claim: aud</Message>
</Error>
<RequestId>xxx</RequestId>
</ErrorResponse>
```

### Invalid Identity Token

Our tokens are missing the attribute **aud (audience)** that seems to be required by the AWS sts API. Pasting my token here: https://jwt.io/ returns:

```
{
  "iss": "kubernetes/serviceaccount",
  "kubernetes.io/serviceaccount/namespace": "default",
  "kubernetes.io/serviceaccount/secret.name": "default-token-f2hkg",
  "kubernetes.io/serviceaccount/service-account.name": "default",
  "kubernetes.io/serviceaccount/service-account.uid": "452155ce-64f6-11ea-9e8b-062a1fe2cdfa",
  "sub": "system:serviceaccount:default:default"
}
```

I have no idea what part of the system generates this token and what value is expected by the STS api yet. I'll keep you in touch if I find something.

**Comment by emohammad** [comment]
@grifx I add the external secrets using helm releases through terraform code to an existing cluster. It wasn't working for me but some how if i delete the external secrets pod and let deployment spin up another on its own then it starts working. I am guessing its something to do with caching or may be an initial delay.

I haven't figured out the root cause yet but after the helm release is deployed i simply delete the pod and got it working

**Comment by grifx** [comment]
I redeployed it a fair amount of times.

@emohammad can you double check that the caller identity is the Role of the serviceaccount and not the role of your ec2 worker node. (You can use npx, code snippet provided above)

Also can you decode your JWT TOKEN 
`cat $AWS_WEB_IDENTITY_TOKEN_FILE`
using jwt.io. A valid token would help me to debug this issue.

Thank you,

**Comment by emohammad** [comment]
@grifx yes i verified the caller identity and it is using service account role and not node worker role. In my case redeploying didn't help. After deploying release i simply deleted the secret manager pod using kubectl delete and the existing Kubernetes deployment will recreate the pod as soon as you manually delete it and then it starts working.

Before i delete the pod aws caller identity is shown as node worker role in the pod and after delete i see service account role being assumed

**Comment by grifx** [comment]
I'm getting closer and closer.
I have a running pod with another container that contains a valid token.

**The tokens are completely different** 
`kubernetes.io/serviceaccount !== eks.amazonaws.com/serviceaccount`

When I describe a pod with a proper token I get:

```
    Mounts:
      /var/run/secrets/eks.amazonaws.com/serviceaccount from aws-iam-token (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from pod-iam-identity-token-q5nzv (ro)
```

When I describe the external-secret pod I get

```
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from pod-iam-identity-token-q5nzv (ro)
```

I'm not sure how to fix this but basically I believe the setup would work with this missing mount was present:

`/var/run/secrets/eks.amazonaws.com/serviceaccount from aws-iam-token (ro)`

**Comment by DWSR** [comment]
Just ran into this. Looks like the container runs as the user `node`, which causes issues with reading the token file if the `fsGroup` is not set to `1000`. Running the snippet from [this post](https://github.com/godaddy/kubernetes-external-secrets/issues/290#issuecomment-599849208) without the `fsGroup` set, I get the following:

```
> Error [CredentialsError]: Missing credentials in config
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at TokenFileWebIdentityCredentials.load (/app/node_modules/aws-sdk/lib/credentials/token_file_web_identity_credentials.js:163:28)
    at TokenFileWebIdentityCredentials.coalesceRefresh (/app/node_modules/aws-sdk/lib/credentials.js:205:12)
    at TokenFileWebIdentityCredentials.refresh (/app/node_modules/aws-sdk/lib/credentials/token_file_web_identity_credentials.js:119:10)
    at TokenFileWebIdentityCredentials.get (/app/node_modules/aws-sdk/lib/credentials.js:122:12)
    at getAsyncCredentials (/app/node_modules/aws-sdk/lib/config.js:374:24)
    at Config.getCredentials (/app/node_modules/aws-sdk/lib/config.js:394:9)
    at Request.VALIDATE_CREDENTIALS (/app/node_modules/aws-sdk/lib/event_listeners.js:81:26)
    at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:102:18) {
  message: 'Missing credentials in config',
  errno: -13,
  syscall: 'open',
  code: 'CredentialsError',
  path: '/var/run/secrets/eks.amazonaws.com/serviceaccount/token',
  time: 2020-03-18T03:05:43.551Z,
  originalError: {
    message: 'Could not load credentials from TokenFileWebIdentityCredentials',
    errno: -13,
    syscall: 'open',
    code: 'CredentialsError',
    path: '/var/run/secrets/eks.amazonaws.com/serviceaccount/token',
    time: 2020-03-18T03:05:43.551Z,
    originalError: {
      errno: -13,
      syscall: 'open',
      code: 'EACCES',
      path: '/var/run/secrets/eks.amazonaws.com/serviceaccount/token',
      message: "EACCES: permission denied, open '/var/run/secrets/eks.amazonaws.com/serviceaccount/token'"
    }
  }
}
```

Following all of the instructions from [this post](https://github.com/godaddy/kubernetes-external-secrets/issues/290#issuecomment-593817996) helped solve the issue.

**Comment by grifx** [comment]
# 🎉  I found the issues!

I'm using **EKS 1.15**

- I was initially using the wrong token using Env Variables (`/run/secrets/kubernetes.io/serviceaccount/token`)
- Setting the AWS ENV variables used by the sdk Credential Provider **(even with the right values!)** is unnecessary and causes the pod not to mount the volume that contains the right token: `/var/run/secrets/eks.amazonaws.com/serviceaccount from aws-iam-token (ro)`
- Both `fsGroup: 65534` and `fsGroup: 1000` are working for me. I can only suggest to use 1000 since apparently using 65534 is causing some issues in some environments.

Working values:
```
env:
  AWS_REGION: ap-southeast-2
  LOG_LEVEL: info

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::xxx:role/yyy

fullnameOverride: external-secrets

securityContext:
  fsGroup: 1000
```

**Comment by gubbin** [comment]
Still no luck with EKS 1.13, using info from recent posts to this issue.  Provided logs to AWS support to look at.

**Comment by mkielar** [comment]
@grifx solution helped me, however I already had a pod running external-secrets. To make it work I had to apply the manifest as above, *and* manually delete existing pod. New pod that was spawned after, properly assumed IAM Role from ServiceAccount and was able to get the secret.

**Comment by emoyer0928** [comment]
I have the same issue with EKS 1.15 and kubernetes-external-secrets 3.2.0.

I see the role ARN, web identity token file, and both mounts when I describe the pod:
```
    Environment:
      AWS_DEFAULT_REGION:            us-east-1
      AWS_REGION:                    us-east-1
      LOG_LEVEL:                     info
      METRICS_PORT:                  3001
      POLLER_INTERVAL_MILLISECONDS:  10000
      VAULT_ADDR:                    http://127.0.0.1:8200
      AWS_ROLE_ARN:                  arn:aws:iam::X:role/roleY
      AWS_WEB_IDENTITY_TOKEN_FILE: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
    Mounts:
      /var/run/secrets/eks.amazonaws.com/serviceaccount from aws-iam-token (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from roleY-token-tf527 (ro)
...
Volumes:
  aws-iam-token:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  86400
```

This makes me think that the service account is correctly linked to the IAM role.

The error is the logs show that it is using the worker node role, which does not have access to the secret.  It is not using the role listed in the AWS_ROLE_ARN pod environment variable.

**Comment by mzupan** [comment]
closing this as I finally tested

https://github.com/godaddy/kubernetes-external-secrets/issues/290#issuecomment-600416118

And things work

**Comment by Niksko** [comment]
FYI, this seems like it will actually be fixed by this commit: https://github.com/godaddy/kubernetes-external-secrets/commit/27ba7e1551c3a34091301dad6d31c8854397837d

To save you some time, you need the change to the Dockerfile to use `user 1000`, you can't just modify an existing deployment with:

```
securityContext:
  runAsNonRoot: true
```

because your container status will show

```
    state:
      waiting:
        message: container has runAsNonRoot and image has non-numeric user (node),
          cannot verify user is non-root
        reason: CreateContainerConfigError
```

**Comment by hgibsonqb** [comment]
I may be late to the party here, but what version of awscli do you have in the container? 

Only awscli v2 can parse the variables AWS_IAM_ROLE and AWS_WEB_IDENTITY_TOKEN_FILE. 

If you have version 1 installed (for example if you installed on a debian container with `apt install awscli` instead of installing with pip) it will ignore those env vars and pull config from the node role instead.
