### ISSUE TITLE
Add CRD to helm chart

### ISSUE THREAD

**Issue by yarinm** [godaddy/kubernetes-external-secrets#300]
For some reason it's missing from the chart and it's not documented to manually install it.

**Comment by Flydiverny** [comment]
Currently it is installed or updated by the service during startup. Probably not ideal :)

**Comment by yarinm** [comment]
It's really not, the helm-chart should have the ability to pre-install it. 
It's really useful on new-clusters scenario where exterrnal-secrets isn't already installed and I want to install my charts one by one without failing.

**Comment by Flydiverny** [comment]
For now all I can offer is that the crd used is available here https://github.com/godaddy/kubernetes-external-secrets/blob/master/crd.yaml
