### ISSUE TITLE
Can't partially update a secret that already exists

### ISSUE THREAD

**Issue by yukin01** [godaddy/kubernetes-external-secrets#309]
If the target secret already exists, it will be replaced by the PUT method.
I think it is better to use the PATCH method, but is there a reason for that?

https://github.com/godaddy/kubernetes-external-secrets/blob/fb284550d5987cf995bf64ca5585250714bd0cc5/lib/poller.js#L159

**Comment by Flydiverny** [comment]
I think patching seems weird as it might not be what you expect as there would be a mismatch.

It's similar to how a cronjob spec creates a job or a deployment creates the pod, we are tying to keep the same behaviours as one would be used to and expect from existing kubernetes solutions. (please correct me if Im wrong 😅 )

When you remove the external secret the secret created will also be removed, which would be odd if it was patched. 

So I suppose use a different name if you don't want to overwrite?

I guess we could fail nowadays if a secret already exists and isn't managed by KES, but earlier this information (ie. ownerReference) wasn't tracked and there was no way to know if the secret was created by KES or already existing. So it would still break migrations from versions <1.3.0

**Comment by yukin01** [comment]
Thank you so much for your kind response.

I see, this behavior is meant to reflect the backend updates to the Secret, not to override the Secret defined outside of KES.

After all, if a Secret with the same name already exists, does that mean that we need to be careful not to duplicate names because it will be updated when KES first creates the Secret?

**Comment by Flydiverny** [comment]
Yes, if there is an existing secret with the same name as the external secret it will be overwritten by the secret generated by the external secret resource.
