### ISSUE TITLE
Mounting external secrets

### ISSUE THREAD

**Issue by gnaazr95** [godaddy/kubernetes-external-secrets#326]
Hi,

When mounting external secrets, does the value get Base64 decoded in the created files? According to K8 documentation, it should be decoded however the files that are being created on my mounted path still contain the encoded data. When I tested this out locally hardcoding this encoded data in a Secret rather than an ExternalSecret, the files contained data in decoded format as expected. Currently using AWS Secrets Manager.

**Comment by silasbw** [comment]
Can you help us repro?  What's the value you look like that you'r storing in AWS SM?  Can you share you `ExternalSecret` manifest?

**Comment by gnaazr95** [comment]
Sure. I essentially got the output from: cat keystore.jks | base64 and put that in Secrets Manager as a string (not a key-value).

**Comment by gnaazr95** [comment]
This is my ExternalSecret manifest: 

`apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: tenant-shasta-catalog-keystore
secretDescriptor:
  backendType: secretsManager
  roleArn: arn:aws:iam::627188849628:role/aws_gwre-ccs-dev_tenant_shasta_developer
  data:
    - key: tenant-shasta-catalog-keystore/keystore-credentials
      name: keystore-credentials`

**Comment by gnaazr95** [comment]
This is my ExternalSecret manifest: `apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: external-secret-gnaazr95
secretDescriptor:
  backendType: secretsManager
  roleArn: appropriate-role-arn
  data:
    - key: external-secret-gnaazr95/keystore-credentials
      name: keystore-credentials`

**Comment by silasbw** [comment]
Are you base64 encoding the secret data before storing it in AWS SM?  You don't need to do that if you are and that could be why you're getting base64 encoded data when you mount the `Secret`

When you create an `ExternalSecret`, the External Secret Controller fetches the data from AWS SM and creates a `Secret` with the base64 encoded version of that data.  If you base64 the data in AWS SM, the External Secret Controller will base64 encode it again.

**Comment by gnaazr95** [comment]
Interesting...that's the issue since I'm encoding before storing it in AWS SM since thats what K8 documentation said to do for regular Secrets. Looks like the ExternalSecret controller works a little different, there's no property option to tell the ExternalSecret controller not to base64 encode the data it retrieves from AWS SM is there?

**Comment by gnaazr95** [comment]
I can confirm that not encoding the string before putting it in AWS SM works as expected. Thanks for the help.
