### ISSUE TITLE
Enhance GCP Secret Manager Backend - Remove metadata info from secret key

### ISSUE THREAD

**Issue by karan-kap** [godaddy/kubernetes-external-secrets#341]
This ticket is related to https://github.com/godaddy/kubernetes-external-secrets/pull/301#issuecomment-608409026

Would like to propose enhancements in the  current nomenclature being used when passing key to the GCP Secret Manager backend. The existing implementation takes the complete URI as part of the key i.e. projects/111122223333/secrets/my-secret/versions/latest. This means that the metadata information (i.e. project id) is being passed with the key. 

Also, GCP Secret manager follows a very simplistic approach when defining secret keys, there is no support yet for hierarchy / tagging, thus secret key naming convention should align with with the way those are defined in GCP.

Fix to this is to pass the project id in the spec (as optional) and if its missing, then can be picked up from the SA credentials.

Additionally, version can be another key under "data" section and again as optional. If not passed, then the GCP secret manager backend will always fetch the latest one.

**Comment by Flydiverny** [comment]
#347 was merged so closing this
