### ISSUE TITLE
runAsNonRoot breaks the container

### ISSUE THREAD

**Issue by saranicole** [godaddy/kubernetes-external-secrets#364]
Trying to use the default runAsNonRoot securityContext set to true in the Helm chart values.yaml file I get the following:

```
NAME                                                            READY   STATUS                       RESTARTS   AGE
external-secrets-kubernetes-external-secrets-788587567f-jf9fp   0/1     CreateContainerConfigError   0          18s
```

Kubectl get events reveals an error:

`19m         Warning   Failed                                                                                                              pod/external-secrets-kubernetes-external-secrets-765bc54796-26fgp    Error: container has runAsNonRoot and image has non-numeric user (node), cannot verify user is non-root`

If I set runAsNonRoot to false or use the following it works:

```
securityContext:
  runAsUser: 999
```

Not sure if this is the right answer though - what is the intent of this value and what should it be set to?

**Comment by iAnomaly** [comment]
Same issue. The new default value for `securityContext` is not compatible with the `godaddy/kubernetes-external-secrets:3.2.0` image.

**Comment by Flydiverny** [comment]
Aye the chart on master will not work until the new version :)

If you want the latest released chart please get it from the chart repo

If you are not running helm for your cluster and just want the manifests you can do something like:
```sh
helm repo add external-secrets https://godaddy.github.io/kubernetes-external-secrets/
helm fetch --untar external-secrets/kubernetes-external-secrets
helm template --name release-name --output-dir ./output_dir ./kubernetes-external-secrets/
```

Or you can download them manually from here: https://github.com/godaddy/kubernetes-external-secrets/blob/master/docs/

Alternatively just override the default value `securityContext: {}`, should probably work until the new version is released, or make a docker image from the master branch and it should also work.

**Comment by mariusv** [comment]
Technically this is not an bug and has an easy solution which is:
1. use the latest docker image: `3.2.0`
2. in your local `values.yaml` add
```
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
```
3. profit
