### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by ChrisBellewVgw** [godaddy/kubernetes-external-secrets#384]
I just noticed that on 
https://www.godaddy.com/engineering/2019/04/16/kubernetes-external-secrets/
there is a typo in one of the examples

```
kind: ExtrenalSecret
```

**Comment by Flydiverny** [comment]
Thanks for reporting! The blog post in general doesn't reflect the latest API and I'm not sure if anyone will update it :) 

Since this is on the godaddy blog and not something we can edit in the repo I'm taking the liberty of closing this!
