### ISSUE TITLE
Build Community via Kubernetes Slack

### ISSUE THREAD

**Issue by hfuss** [godaddy/kubernetes-external-secrets#388]
Proposing the creation and support of a #kubernetes-external-secrets channel in the kubernetes.slack.com community and link it to the documentation. Example projects with Slack channels or orgs:
- [KIAM](https://kubernetes.slack.com/archives/CBQLKVABH)
- [CertManager](https://kubernetes.slack.com/archives/C4NV3DWUC)
- [Prometheus](https://cloud-native.slack.com/archives/C167KFM6C)
- [ArgoCD](https://argoproj.slack.com/archives/CASHNF6MS)

I am happy to create it, etc. just opening this issue to try to gauge the GoDaddy folks' interest in being apart of something like that.

**Comment by Flydiverny** [comment]
I was considering it not to long ago, but didn't pursue it. While there is a [slack](https://godaddy-oss.slack.com/archives/CEUMRK5B8) its not really used a lot.

**Comment by Flydiverny** [comment]
Guess I cut my message a bit short 😄But all in all I think its a good idea.

**Comment by muenchdo** [comment]
How about requesting a channel on the official Kubernetes Slack for now instead of setting up an entirely new Slack workspace?

**Comment by Flydiverny** [comment]
@muenchdo I don't think there was any intention of setting up a new slack workspace. What @hfuss suggested was on the official kubernetes slack 🙂 and I just said there's a channel in the godaddy oss slack.

But I'd say set one up!

**Comment by muenchdo** [comment]
Ah right @Flydiverny, somehow missed that 😛 I just requested the channel.

**Comment by Flydiverny** [comment]
Slack channel is now available! #external-secrets :)
