### ISSUE TITLE
Unable to specify a Vault namespace in externalsecret manifest

### ISSUE THREAD

**Issue by reach2ravikumarp** [godaddy/kubernetes-external-secrets#390]
We are using enterprise vault server where we have couple of vault namespaces. I was trying to integrate my vault server using extrernalsecret with specific vault namespace, unable to do the same. Can some one look into it or point me with correct config... cc. @silasbw @rxmarbles

**Comment by chefbob** [comment]
We also have this requirement.

**Comment by EricHorst** [comment]
Namespace support added in #403, its configured centrally, not in an ExternalSecret. Does that help?

**Comment by Flydiverny** [comment]
Closing this as support for namespace was added in #403, if you have other need reopen.

**Comment by reach2ravikumarp** [comment]
Thanks @Flydiverny @EricHorst , I am able to configure Vault  namespace with External secret and able to retrieve secrets from it.

cc @chefbob
