### ISSUE TITLE
Failed to get /openapi/v2 and /swagger.json

### ISSUE THREAD

**Issue by Sytten** [godaddy/kubernetes-external-secrets#392]
Hello all!
I am trying to deploy the service to a GKE cluster (`1.15.11-gke.11`) using helm v3 and terraform without any luck.

Here is my setup:
```terraform
module "external_secrets_identity" {
  source = "../../common/workload-identity"

  project   = var.project
  name      = "external-secrets"
  namespace = "kube-system"
}

resource "helm_release" "external_secrets" {
  name       = "external-secrets"
  repository = "https://godaddy.github.io/kubernetes-external-secrets/"
  chart      = "kubernetes-external-secrets"
  version    = "3.3.0"
  namespace  = "kube-system"

  set {
    name  = "env.POLLER_INTERVAL_MILLISECONDS"
    value = "60000"
  }

  set {
    name  = "serviceAccount.create"
    value = false
  }

  set {
    name  = "serviceAccount.name"
    value = module.external_secrets_identity.k8s_service_account_name
  }
}
```

The workload identity is just creating a GCP and k8s service account (and linking them).
It installs, but when starting it crashes:
```
{"level":30,"time":1590608709115,"pid":17,"hostname":"external-secrets-kubernetes-external-secrets-6664b4fccf-v6n27","msg":"loading kube specs"}
Error: Failed to get /openapi/v2 and /swagger.json: connect ECONNREFUSED 127.0.0.1:8080
    at /app/node_modules/kubernetes-client/lib/swagger-client.js:58:15
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async main (/app/bin/daemon.js:32:3)
npm info lifecycle kubernetes-external-secrets@3.3.0~start: Failed to exec start script
```

Not so sure what I am missing...

**Comment by Sytten** [comment]
- Debugging further, I tried a plain old installation with the helm v3 cli and it worked (helm 3.2.1). 
- Tried again with removing the `name  = "serviceAccount.create"` and it worked
It seems like the issue is with the service account to me.

**Comment by Sytten** [comment]
I don't know helm/kube enough to know why it doesnt work when you create the service account before (I guess its because of missing labels?). So I decided to just specify a fix name so I can still predict my workload identity and let the chart create the service account. I would very much like to know why it doesnt work though if someone has an explanation.

**Comment by Sytten** [comment]
For reference this is my final terraform:
```terraform
module "external_secrets_identity" {
  source = "../../common/workload-identity"

  project     = var.project
  name        = "external-secrets"
  k8s_sa_name = "external-secrets"
  namespace   = "kube-system"

  dependencies = var.dependencies
}

resource "helm_release" "external_secrets" {
  depends_on = [module.external_secrets_identity]

  name       = "external-secrets"
  repository = "https://godaddy.github.io/kubernetes-external-secrets/"
  chart      = "kubernetes-external-secrets"
  version    = "3.3.0"
  namespace  = "kube-system"

  set {
    name  = "env.POLLER_INTERVAL_MILLISECONDS"
    value = "60000"
  }

  set {
    name  = "fullnameOverride"
    value = "external-secrets"
  }

  set {
    name  = "serviceAccount.name"
    value = "external-secrets"
  }

  set {
    name  = "serviceAccount.annotations.iam\\.gke\\.io/gcp-service-account"
    value = module.external_secrets_identity.gcp_service_account_email
  }
}
```

My workload identity module is very similar to https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/v9.0.0/modules/workload-identity

I think that #344 will also be necessary if you create the CRD in terraform in the same apply (otherwise it will fail because the chart might not had time to install).

**Comment by gaahrdner** [comment]
Thanks @krjackso, this solved the problem for me as well. For future people that stumble across this issue, the `automount_service_account_token` input is part of Google's workload-identity module.
