### ISSUE TITLE
Not able to create a secret using externalsecret

### ISSUE THREAD

**Issue by dhineshbabuelango** [godaddy/kubernetes-external-secrets#415]
Hi Team, we are using the ES(External Secret) in our EKS cluster and it works fine for almost all the external secret. There is one external secret for which when this ES pod trying to create external secret, it failed with below error 

**You can't perform this operation on the secret because it was marked for deletion**

The secret exits and it is not marked for deletion, I even raised case with AWS and they also confirmed the secret exists, deleted on also not showing anything but still the pod not able to create secret

![image](https://user-images.githubusercontent.com/51995628/85510247-b3856680-b629-11ea-9bf7-fd3995cacb75.png)

**{"level":30,"time":1592976611293,"pid":16,"hostname":"external-secrets-kubernetes-external-secrets-6477d4f868-njtwq","msg":"upserting secret mi-crypt-util-secret-external","v":1}
{"level":50,"time":1592976611299,"pid":16,"hostname":"external-secrets-kubernetes-external-secrets-6477d4f868-njtwq","msg":"failure while polling the secrets","v":1}
{"level":50,"time":1592976611299,"pid":16,"hostname":"external-secrets-kubernetes-external-secrets-6477d4f868-njtwq","type":"Error","stack":"InvalidRequestException: You can't perform this operation on the secret because it was marked for deletion.\n    at Request.extractError (/app/node_modules/aws-sdk/lib/protocol/json.js:51:27)\n    at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:106:20)\n    at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\n    at Request.emit (/app/node_modules/aws-sdk/lib/request.js:683:14)\n    at Request.transition (/app/node_modules/aws-sdk/lib/request.js:22:10)\n    at AcceptorStateMachine.runTo (/app/node_modules/aws-sdk/lib/state_machine.js:14:12)\n    at /app/node_modules/aws-sdk/lib/state_machine.js:26:10\n    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:38:9)\n    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:685:12)\n    at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:116:18)","message":"You can't perform this operation on the secret because it was marked for deletion.","code":"InvalidRequestException","time":"2020-06-24T05:30:11.299Z","requestId":"3c1db42f-5eb2-49cf-ac54-925123049662","statusCode":400,"retryable":false,"retryDelay":39.01860019913792,"msg":"You can't perform this operation on the secret because it was marked for deletion.","v":1}**

**Comment by Flydiverny** [comment]
No idea, this error is from the aws-sdk :shrug:

**Comment by VinothChinnadurai** [comment]
@dhineshbabuelango might be due to this i guess https://aws.amazon.com/premiumsupport/knowledge-center/delete-secrets-manager-secret/

**Comment by dhineshbabuelango** [comment]
@VinothChinnadurai Thanks for sharing this details. But I never deleted the secret and confirmed with AWS as well and also the deleted on column is blank. I restarted the external secrets pod and the external secret that I have created and then issue was solved. Now waiting for the reoccurrence.

**Comment by Flydiverny** [comment]
Closing this as the issue doesn't seem to originate from external secrets.
