### ISSUE TITLE
[Feature Request] Support versionId of AWS Secrets Manager

### ISSUE THREAD

**Issue by sonots** [godaddy/kubernetes-external-secrets#435]
I found that the `external-secrets` supports `versionStage`, but not `versionId`.
I am glad if `external-secrets` supports `versionId`, too.

**Comment by acgs771126** [comment]
Can support versionID setting in dataFrom, too?

**Comment by Flydiverny** [comment]
@acgs771126 please open a new issue. With current syntax I'm not sure we can tho. dataFrom is a list of strings/keys

**Comment by acgs771126** [comment]
@Flydiverny  thanks for your reply, I created [new issue](https://github.com/external-secrets/kubernetes-external-secrets/issues/685) for this feature request.
