### ISSUE TITLE
helm template --namespace not applying namespace to Service or Deployment

### ISSUE THREAD

**Issue by rvaidya** [godaddy/kubernetes-external-secrets#470]
When I use helm template with the --namespace argument, the namespace is only applied to the service account, so the Service and Deployment aren't getting applied.

This may apply to helm install as well.

The command I'm using:

helm template $HELM_CHART --output-dir $INSTALL_DIR --namespace $NAMESPACE --values values.yaml

**Comment by tzilistgoop** [comment]
Likely they will need to add `namespace: {{ .Release.Namespace }}` to the metadata

**Comment by Flydiverny** [comment]
Fixed in #471
