### ISSUE TITLE
Prometheus metrics don't follow best practices

### ISSUE THREAD

**Issue by aabouzaid** [godaddy/kubernetes-external-secrets#489]
Hello,

Currently, KES Prometheus metrics (`last_state` and `sync_calls`) don't follow [Prometheus metric names best practices](https://prometheus.io/docs/practices/naming/#metric-names).

That's because:
> A metric name...
> - ...should have a (single-word) application prefix relevant to the domain the metric belongs to. [...]
> - ...should have a suffix describing the unit, in plural form. [...]

Without a prefix, suffix, or unites it's hard to identify KES metrics and work them.

I'd be happy to make a PR for this change, but since it's a breaking change, I'd like to hear which strategy to follow to deprecate the old metrics.

**Comment by lwille** [comment]
I'd suggest the following strategy to introduce the new metric and phase out the old one:
- implement new prefixed metric in addition to the old one
- a new metric doesn't break anything, so it can be released any time
- mark the "old" metric deprecated in the code and schedule its deletion for the next major version release

**Comment by Flydiverny** [comment]
Sounds good, PR welcome 😄
