### ISSUE TITLE
isBinary field does not work with the property field in Azure backend

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [godaddy/kubernetes-external-secrets#494]
According to the PR at #311, the `isBinary` field doesn't work with `property` field for Azure backend. I have a idea to solve this and I am creating this issue to track it.

**Comment by SayakMukhopadhyay** [comment]
Essentially I am thinking of an Azure specific option `propertyAzure` that will be handled by the Azure backend only and won't trip the JSON.parse in the kv backend. This would help the Azure backend have the same compatibility options that is present without the `isBinary` field. Let me know how this sounds.

**Comment by Flydiverny** [comment]
See #495
