### ISSUE TITLE
eks fargate issue facing ERROR, Missing credentials in config

### ISSUE THREAD

**Issue by yongxiuuu** [godaddy/kubernetes-external-secrets#506]
Hello I am facing missing credentials in config error for fargate eks. I followed the steps from here

https://github.com/godaddy/kubernetes-external-secrets/pull/416
and also 
https://github.com/godaddy/kubernetes-external-secrets/pull/414

tried both but no success :( This is the logs I got from the pod:

{“level”:50,“time”:1602036267400,“pid”:17,“hostname”:“external-secret-2kubernetes-external-secrets-886db7b86-9xnf4”,“message”:“Missing credentials in config”,“errno”:“ETIMEDOUT”,“code”:“CredentialsError”“originalError”:{“message”:“Could not load credentials from any providers”,“errno”:“ETIMEDOUT”,“code”:“CredentialsError”,“syscall”:“connect”,,“originalError”:{“message”:“EC2 Metadata roleName request returned

**Comment by Flydiverny** [comment]
#452

**Comment by yongxiuuu** [comment]
I just tried  #452. 
I had supplied the helm chart value as mentioned in the thread. I still got the same error message :( Thank you

**Comment by yongxiuuu** [comment]
Hi @Flydiverny can check with you for this particular role arn:aws:iam::111111111:role/eksctl-fargate-test-kes-iamserviceaccount-role --> what kind of policy you using?

**Comment by Flydiverny** [comment]
`arn:aws:iam::111111111:role/eksctl-fargate-test-kes-iamserviceaccount-role`

Only has a trust relationship of, _**NOTE** that this permission would allow **any** service account to assume this role_
```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Federated": "arn:aws:iam::111111111:oidc-provider/oidc.eks.eu-west-1.amazonaws.com/id/F5C083E55DB8AE8A685E5F11E3DDCAB8"
      },
      "Action": "sts:AssumeRoleWithWebIdentity",
      "Condition": {
        "StringLike": {
          "oidc.eks.eu-west-1.amazonaws.com/id/F5C083E55DB8AE8A685E5F11E3DDCAB8:sub": "system:serviceaccount:*"
        }
      }
    }
  ]
}
```

For more details check the EKS user guide
https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html
https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-technical-overview.html
