### ISSUE TITLE
AWS Region should be required

### ISSUE THREAD

**Issue by kenske** [godaddy/kubernetes-external-secrets#51]
The config defaults to `us-west-2` for the AWS region which seems arbitrary and caused some pain while troubleshooting. Instead, the AWS region should be set explicitly in the deployment. The documentation should be updated to specify where to modify the value if needed.

**Comment by JacopoDaeli** [comment]
Created a PR to fix this issue. Adding a `helm` chart is going to be the next step for simplifying how people can run the daemon with custom config.
