### ISSUE TITLE
hashicorp vault

### ISSUE THREAD

**Issue by bitsofinfo** [godaddy/kubernetes-external-secrets#62]
Could this in theory support Hashicorp Vault?

**Comment by silasbw** [comment]
Yes it could!  We'd love a PR to add support :)

**Comment by JacopoDaeli** [comment]
@bitsofinfo would you like to do a PR to add support for Vault?

**Comment by bitsofinfo** [comment]
I don't have the time currently, was just curious if it would be possible

**Comment by bboerst** [comment]
Been working on this over here:  https://github.com/tunein/kubernetes-external-secrets/tree/vault-backend
Let me know if you want me to open up a PR to get some more eyes looking at this.  It's working but I'm sure some optimizations can be made.

**Comment by cmacrae** [comment]
Nice work @bboerst :clap: I think it'd be great to get this opened as an MR to get some traction and get people reviewing. Are there any particular points in your implementation you feel need extra scrutiny?  
I've had a look over it, and it's looking good to me :ok_hand:

**Comment by jeffpearce** [comment]
@bboerst please open a PR - we'd love to get this integrated
