### ISSUE TITLE
Support for Parameter Store

### ISSUE THREAD

**Issue by kenske** [godaddy/kubernetes-external-secrets#86]
Now that AWS parameter store has the option for increased API rates, are there any plans to support it?

**Comment by silasbw** [comment]
We'd welcome a PR contributing that support :)

**Comment by Flydiverny** [comment]
I'm confused is there support for parameter store or not? :D 
Theres a backend implementation for system manager https://github.com/godaddy/kubernetes-external-secrets/blob/master/lib/backends/system-manager-backend.js
Isn't this using parameter store?
Not that I can get the system manager backend to work, seems to poll secrets but then fail parsing :)

**Comment by JacopoDaeli** [comment]
@Flydiverny I started adding support for it when I first built External Secrets.
However, we never really used that and tested. It would be great if you can test it out and make it work if necessary.

**Comment by Sytten** [comment]
Any work on that?

**Comment by Flydiverny** [comment]
@Sytten I didn't look on it anymore from my end at least, as we decided to migrate to secrets manager anyway.

**Comment by Sytten** [comment]
I will start with SM, but SSM is basically free so I might end up writing the necessary pieces.
