### ISSUE TITLE
No way to install via kubectl?

### ISSUE THREAD

**Issue by cwiggs** [godaddy/kubernetes-external-secrets#89]
I was directed here from this blog: https://godaddy.github.io/2019/04/16/kubernetes-external-secrets/

I was looking into using this tool but noticed that recently deploying via kubectl was removed and helm is now the official way to install.  Is there some type of workaround or plans to re-introduce deploying with kubectl?  Having to install helm just to install this tool is a real bummer.

PR where helm was setup as the official way to install: #68 
When external-secrets.yml was removed: #70 
Someone else asked a similar question here: #72

**Comment by silasbw** [comment]
Yes, we've been planning on re-adding this!

Thanks for creating the issue to track.  We'd welcome a PR too :)

**Comment by cwiggs** [comment]
Can you give me more insight into what needs to be done or why the kubectl option was removed?  I have a k8 cluster I can test with and am comfortable with debugging stuff.  Not sure if I have time to add a ton to the code base though.

**Comment by silasbw** [comment]
I'll merge https://github.com/godaddy/kubernetes-external-secrets/pull/90, but we need a few improvements:

- [ ] Update README.md with instructions
- [ ] Decide how we want apply runtime configuration (_e.g._, AWS_REGION)

For the runtime config, we could add a ConfigMap to the external-secrets.yml file that has a default AWS_REGION; and update the README.md with instructions on how to update it and restart the controller.

Does that seem reasonable @cwiggs ?

**Comment by Flydiverny** [comment]
Should we close this with the merge of #212 ?
cc @keweilu @silasbw
