### ISSUE TITLE
Delete secret when externalsecret is removed

### ISSUE THREAD

**Issue by Flydiverny** [godaddy/kubernetes-external-secrets#93]
It would be nice if the created secret was removed if I remove the external secret resource.

**Comment by silasbw** [comment]
Agreed.  We'd gladly work to merge any PR that makes this a configurable option.

**Comment by sparkacus** [comment]
Is this a configurable option?

For my needs I don't want KES to be able to delete a Kubernetes secret, even if it was initially created via externalsecrets.
